<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE TEI [
    <!ELEMENT TEI (header,facsimile?,text+)>
    <!ELEMENT header (#PCDATA)>
    <!ELEMENT s (#PCDATA)>
    <!ELEMENT facsimile (#PCDATA)>
    <!ELEMENT text (#PCDATA | s)*>
    <!ATTLIST header type CDATA #FIXED "intestazione">
    <!ATTLIST header lang (eng|it|fr) #IMPLIED>
    <!ATTLIST text id ID #REQUIRED>
    <!ATTLIST facsimile ref IDREFS #IMPLIED>
    ]>
<TEI>
<header lang="eng">
testo
</header>
<facsimile ref="t1">
testo
</facsimile>
<text id="t1"> 
testo
<s>
Nuovo testo
</s>
</text>
</TEI>